fizzler1 <- Entities.CreateByClassname("trigger_multiple")
fizzler1.__KeyValueFromInt("Solid", 3)
fizzler1.SetAbsOrigin(Vector(352, 64, -350))
fizzler1.SetSize(Vector() - Vector(80, 80, 32), Vector(80, 80, 0))
fizzler1.__KeyValueFromString("targetname", "prevent_softlock_fizzler")
fizzler1.__KeyValueFromInt("spawnflags", 64)
EntFireByHandle(fizzler1, "enable", "", 0, null, null)
EntFireByHandle(fizzler1, "addoutput", "OnStartTouch !activator:silentdissolve", 0, null, null)
//EntFireByHandle(fizzler1, "addoutput", "OnStartTouch !activator:runscriptcode:printl(1)", 0, null, null)
//EntFireByHandle(fizzler1, "addoutput", "OnEndTouch !activator:runscriptcode:printl(0)", 0, null, null)

fizzler2 <- Entities.CreateByClassname("trigger_multiple")
fizzler2.__KeyValueFromInt("Solid", 3)
fizzler2.SetAbsOrigin(Vector(608, 64, -350))
fizzler2.SetSize(Vector() - Vector(80, 80, 32), Vector(80, 80, 0))
fizzler2.__KeyValueFromString("targetname", "prevent_softlock_fizzler")
fizzler2.__KeyValueFromInt("spawnflags", 64)
EntFireByHandle(fizzler2, "enable", "", 0, null, null)
EntFireByHandle(fizzler2, "addoutput", "OnStartTouch !activator:silentdissolve", 0, null, null)

fizzler3 <- Entities.CreateByClassname("trigger_multiple")
fizzler3.__KeyValueFromInt("Solid", 3)
fizzler3.SetAbsOrigin(Vector(160, -96, -366))
fizzler3.SetSize(Vector() - Vector(80, 80, 32), Vector(80, 80, 0))
fizzler3.__KeyValueFromString("targetname", "prevent_softlock_fizzler")
fizzler3.__KeyValueFromInt("spawnflags", 64)
EntFireByHandle(fizzler3, "enable", "", 0, null, null)
EntFireByHandle(fizzler3, "addoutput", "OnStartTouch !activator:silentdissolve", 0, null, null)