killTrig <- Entities.CreateByClassname("trigger_multiple")
killTrig.SetAbsOrigin(Vector(-3648, -1162, -960))
killTrig.SetSize(Vector() - Vector(1898, 1214, 0), Vector(1898, 1214, 1))
killTrig.__KeyValueFromInt("Solid", 3)
killTrig.__KeyValueFromString("targetname", "prevent_softlock_kill_trigger")
killTrig.__KeyValueFromInt("spawnflags", 64)
EntFireByHandle(killTrig, "enable", "", 0, null, null)
EntFireByHandle(killTrig, "addoutput", "OnStartTouch !activator:dissolve", 0, null, null)
EntFireByHandle(killTrig, "addoutput", "OnStartTouch !activator:sethealth:-99999999:0.01", 0, null, null)

diskKillTrig <- Entities.CreateByClassname("trigger_multiple")
diskKillTrig.SetAbsOrigin(Vector(1269, -1477.5, -1408))
diskKillTrig.SetSize(Vector() - Vector(1358, 1811.5, 0), Vector(1358, 1811.5, 1))
diskKillTrig.__KeyValueFromInt("Solid", 3)
diskKillTrig.__KeyValueFromString("targetname", "prevent_softlock_disk_fizzler")
diskKillTrig.__KeyValueFromInt("spawnflags", 8)
EntFireByHandle(diskKillTrig, "enable", "", 0, null, null)
EntFireByHandle(diskKillTrig, "addoutput", "OnStartTouch !activator:kill", 0, null, null)
EntFireByHandle(diskKillTrig, "addoutput", "OnStartTouch ptemplate_disk_spawn:ForceSpawn", 0, null, null)