killTrig1 <- Entities.CreateByClassname("trigger_hurt")
killTrig1.__KeyValueFromInt("Solid", 3)
killTrig1.SetAbsOrigin(Vector(-9821, -3502, -186))
killTrig1.SetSize(Vector() - Vector(50, 50, 0), Vector(50, 50, 1))
killTrig1.__KeyValueFromString("targetname", "prevent_softlock_pgun_trigger")
killTrig1.__KeyValueFromInt("spawnflags", 64)
killTrig1.__KeyValueFromInt("damagetype", 0)
killTrig1.__KeyValueFromInt("damage", 9999999)
killTrig1.__KeyValueFromInt("damagecap", 9999999)
EntFireByHandle(killTrig1, "enable", "", 0, null, null)

killTrig2 <- Entities.CreateByClassname("trigger_hurt")
killTrig2.__KeyValueFromInt("Solid", 3)
killTrig2.SetAbsOrigin(Vector(-10200, -3500, -186))
killTrig2.SetSize(Vector() - Vector(50, 50, 0), Vector(50, 50, 1))
killTrig2.__KeyValueFromString("targetname", "prevent_softlock_pgun_trigger")
killTrig2.__KeyValueFromInt("spawnflags", 64)
killTrig2.__KeyValueFromInt("damagetype", 0)
killTrig2.__KeyValueFromInt("damage", 9999999)
killTrig2.__KeyValueFromInt("damagecap", 9999999)
EntFireByHandle(killTrig2, "enable", "", 0, null, null)